"""World Cup 2026 Simulator - Tournament simulation functions."""

import pandas as pd
from scipy.stats import poisson
import logging
import random
import sqlite3
import numpy as np 

from third_place_scenarios import THIRD_PLACE_SCENARIOS_BY_GROUPS

logger = logging.getLogger(__name__)



########### CONFIG ############################
from constants import MEAN_GOALS, DB_PATH, N_SIMULATIONS
################################################



############# FUNCTIONS ######################################

# ============================================================
# SECTION 1 — DATA LOADING
# ============================================================
def load_data(db_path=DB_PATH):
    """Load matches and teams from the SQLite database."""
    conn = sqlite3.connect(db_path)
    matches_df = pd.read_sql_query("SELECT * FROM matches", conn)
    teams_df = pd.read_sql_query("SELECT * FROM teams", conn)
    conn.close()
    return matches_df, teams_df

def create_poisson_dist(mean_goals):
    """Returns a Poisson distribution object with the given mean."""
    return poisson(mu=mean_goals)

def generate_goals_scored(poisson_dist):
    """Returns an integer generated by a random draw from the given Poisson distribution."""
    return poisson_dist.rvs()

import numpy as np

def scale_params_by_fifa_points(fifa_points):
    """
    Translates raw FIFA points directly into normal and beta distribution parameters.
    """
    points = max(1100.0, min(1880.0, float(fifa_points)))
    scale_coef = (points - 1100.0) / (1880.0 - 1100.0)
    
    # Baseline shot properties before match-specific tactical suppression
    shot_mean = 7.0 + (10.0 * scale_coef)
    shot_std = 3.0 + (2.0 * scale_coef)
    
    # Shot quality (Beta parameters)
    target_mean_xg = 0.105
    target_variance = 0.024 - (0.004 * scale_coef)
    
    moments_factor = ((target_mean_xg * (1.0 - target_mean_xg)) / target_variance) - 1.0
    beta_alpha = target_mean_xg * moments_factor
    beta_beta = (1.0 - target_mean_xg) * moments_factor
    
    return shot_mean, shot_std, beta_alpha, beta_beta

def simulate_team_match(shot_mean, shot_std, beta_alpha, beta_beta):
    """
    Simulates a single team's match performance.
    """
    num_shots = int(np.round(np.random.normal(shot_mean, shot_std)))
    num_shots = max(0, num_shots)
    
    if num_shots == 0:
        return 0.0, 0
        
    shot_xg_values = np.random.beta(beta_alpha, beta_beta, size=num_shots)
    total_team_xg = np.sum(shot_xg_values)
    
    random_rolls = np.random.random(size=num_shots)
    goals_scored = np.sum(random_rolls < shot_xg_values)
    
    return total_team_xg, goals_scored

def apply_matchup_suppression(a_mean, a_std, b_mean, b_std):
    """
    NEW: Adjusts shot parameters based on the mutual strength of the teams.
    If both teams are elite, they restrict each other's attacking space.
    """
    # If the combined baseline shots exceed a standard open match baseline (e.g., 24.0)
    combined_base_shots = a_mean + b_mean
    
    if combined_base_shots > 24.0:
        # Scale suppression power. The more elite the matchup, the tighter the game.
        # Max suppression caps at around an 18% reduction for Rank 1 vs Rank 1.
        excess = combined_base_shots - 24.0
        suppression_factor = 1.0 - (0.018 * excess) 
        
        a_mean *= suppression_factor
        a_std *= suppression_factor
        b_mean *= suppression_factor
        b_std *= suppression_factor
        
    return a_mean, a_std, b_mean, b_std


# ============================================================
# SECTION 2 — MATCH SIMULATION
# ============================================================
def simulate_group_stage_matches(matches_df: pd.DataFrame, mean_goals: str=MEAN_GOALS) -> pd.DataFrame:
    """ Filter for scheduled matches (not completed yet) and simulate them using the function `generate_goals_scored()`

    Args:
        matches_df (DataFrame): get from load_data()
        mean_goals (str): default to MEAN_GOALS constant

    Returns:
        group_stage_matches (DataFrame): 
    
    """
    dist = create_poisson_dist(mean_goals)

    group_stage_matches = matches_df[
        (matches_df['stage_id'] == 1) & (matches_df['status'] == 'scheduled')
        ].copy()  # Only group stage matches and that not completed yet.
    
    group_stage_matches['home_score'] = group_stage_matches.apply(lambda row: generate_goals_scored(dist), axis=1)
    assert group_stage_matches['home_score'].isnull().sum() == 0, "Error: home_score has null values after simulation"
    
    group_stage_matches['away_score'] = group_stage_matches.apply(lambda row: generate_goals_scored(dist), axis=1)
    assert group_stage_matches['away_score'].isnull().sum() == 0, "Error: away_score has null values after simulation"
    
    group_stage_matches['goal_diff'] = group_stage_matches['home_score'] - group_stage_matches['away_score']
    group_stage_matches['result'] = group_stage_matches.apply(lambda row: 'home_win' if row['goal_diff'] > 0 else ('draw' if row['goal_diff'] == 0 else 'away_win'), axis=1)    
    assert group_stage_matches['result'].isnull().sum() == 0, "Error: result has null values after simulation"  
    
    group_stage_matches['status'] = 'simulated'

    return group_stage_matches

############# with fifa rankings... ###########################

def simulate_match_fifa(home_fifa_pts, away_fifa_pts):
    """
    Simulate a single match using FIFA points model.
    Returns (home_score, away_score, result).
    """
    home_params = scale_params_by_fifa_points(home_fifa_pts)
    away_params = scale_params_by_fifa_points(away_fifa_pts)

    _, home_goals = simulate_team_match(*home_params)
    _, away_goals = simulate_team_match(*away_params)

    if home_goals > away_goals:
        result = 'home_win'
    elif away_goals > home_goals:
        result = 'away_win'
    else:
        result = 'draw'

    return int(home_goals), int(away_goals), result

def simulate_group_stage_matches_fifa(matches_df, teams_df):
    """
    Simulate scores for all unplayed group stage matches using the FIFA
    points model. Each team's shots and shot quality are derived from
    their FIFA ranking points via scale_params_by_fifa_points().

    Only matches with stage_id == 1 and status == 'scheduled' are simulated.
    Completed matches are intentionally excluded to preserve real results.

    Companion function to simulate_group_stage_matches(). Use this when
    running the FIFA strength model. Use simulate_group_stage_matches()
    for the baseline equal-probability Poisson model.

    Args:
        matches_df (pd.DataFrame): Full matches table from DB (all 104 rows).
        teams_df (pd.DataFrame): Teams table from DB. Must contain columns:
            id, fifa_points. All 48 teams must have non-null fifa_points
            before calling this function.

    Returns:
        pd.DataFrame: Copy of the scheduled group stage rows with columns added:
            home_score (int), away_score (int), goal_diff (int),
            result (str: 'home_win' | 'away_win' | 'draw'),
            status (str: 'simulated')

    Raises:
        ValueError: if any team in the scheduled matches has a null fifa_points,
                    or if a team_id in a scheduled match is not found in teams_df.
        AssertionError: if no scheduled group stage matches are found,
                        or if any score values are null after simulation.
    """

    # ── Guard: confirm all teams have fifa_points populated ──────────────
    missing = teams_df[teams_df['fifa_points'].isna()]['team_name'].tolist()
    if missing:
        raise ValueError(
            f"Cannot run FIFA model — missing fifa_points for: {missing}. "
            "Run fifa_points_update.sql to populate all 48 teams."
        )

    # ── Build a fast lookup dict: {team_id: fifa_points} ─────────────────
    fifa_pts_lookup = teams_df.set_index('id')['fifa_points'].to_dict()

    # ── Filter to unplayed group stage matches ────────────────────────────
    group_stage_matches = matches_df[
        (matches_df['stage_id'] == 1) &
        (matches_df['status'] == 'scheduled')
    ].copy()

    assert len(group_stage_matches) > 0, (
        "No scheduled group stage matches found. "
        "Check that stage_id == 1 and status == 'scheduled' rows exist in matches_df."
    )

    # ── Simulate each match ───────────────────────────────────────────────
    home_scores = []
    away_scores = []
    results     = []

    for _, row in group_stage_matches.iterrows():
        home_pts = fifa_pts_lookup.get(row['home_team_id'])
        away_pts = fifa_pts_lookup.get(row['away_team_id'])

        # Guard against a team_id present in matches but missing from teams table
        if home_pts is None:
            raise ValueError(
                f"Match id={row['id']}: home_team_id={row['home_team_id']} "
                "not found in teams_df. Check the teams table for missing rows."
            )
        if away_pts is None:
            raise ValueError(
                f"Match id={row['id']}: away_team_id={row['away_team_id']} "
                "not found in teams_df. Check the teams table for missing rows."
            )

        # Derive shot distribution parameters from each team's FIFA points
        home_params = scale_params_by_fifa_points(home_pts)
        away_params = scale_params_by_fifa_points(away_pts)

        # Simulate each team's performance independently
        _, home_goals = simulate_team_match(*home_params)
        _, away_goals = simulate_team_match(*away_params)

        # Cast to plain int — numpy int64 can cause issues downstream
        home_goals = int(home_goals)
        away_goals = int(away_goals)

        # Determine match result
        if home_goals > away_goals:
            result = 'home_win'
        elif away_goals > home_goals:
            result = 'away_win'
        else:
            result = 'draw'

        home_scores.append(home_goals)
        away_scores.append(away_goals)
        results.append(result)

    # ── Write results back to the DataFrame ──────────────────────────────
    group_stage_matches['home_score'] = home_scores
    group_stage_matches['away_score'] = away_scores
    group_stage_matches['goal_diff']  = (
        group_stage_matches['home_score'] - group_stage_matches['away_score']
    )
    group_stage_matches['result'] = results
    group_stage_matches['status'] = 'simulated'

    # ── Post-simulation assertions ────────────────────────────────────────
    assert group_stage_matches['home_score'].isna().sum() == 0, \
        "home_score has null values after FIFA model simulation."
    assert group_stage_matches['away_score'].isna().sum() == 0, \
        "away_score has null values after FIFA model simulation."

    logger.debug(
        "FIFA model simulated %d group stage matches",
        len(group_stage_matches)
    )

    return group_stage_matches


# ============================================================
# SECTION 3 — STANDINGS & RANKING
# ============================================================
def initial_ranking(final_standings: pd.DataFrame) -> pd.DataFrame:
    """Do an initial rank on points.
    Totals have already been calculated in the final_standings table, so we just need to sort by points, then goal difference, then goals for.

    Args:
        final_standings (DataFrame): generated from function `create_final_standings()`

    Returns:
        rankings (DataFrame): table with ranking based on points, goal difference, goals for
    """
    df = final_standings.copy()

    # get min rank based on points, then goal difference, then goals for
    # highest points gets rank 1, ties gets same rank, next rank is skipped
    df['overall_rank'] = df['points'].rank(method='min', ascending=False) 
    return df


def create_final_standings(group_stage_matches, teams_df):
    """
    Aggregate group-stage match results into final standings per team.
    
    Computes for each team:
    - points (3 for W, 1 for D, 0 for L)
    - goals_for (total goals scored)
    - goals_against (total goals conceded)
    - goal_diff (goals_for - goals_against)
    - matches_played
    - wins, draws, losses
    - head_to_head opponents (for tiebreaker logic)
    
    Args:
        group_stage_matches (pd.DataFrame): Simulated matches from function `simulate_group_stage_matches()` 
        teams_df (pd.DataFrame): Teams table with id, team_name, group columns
    
    Returns:
        pd.DataFrame: Final standings with one row per team, columns:
            team_id, team_name, group_id, matches_played, 
            points, goals_for, goals_against, goal_diff, opponents_beat, opponents_drew_with
    """
    
    standings_data = []
    
    for team_id in teams_df['id'].unique():
        team_name = teams_df[teams_df['id'] == team_id]['team_name'].iloc[0]
        group = teams_df[teams_df['id'] == team_id]['group_letter'].iloc[0]
        
        # Filter matches where this team played (home or away)
        home_matches = group_stage_matches[group_stage_matches['home_team_id'] == team_id]
        away_matches = group_stage_matches[group_stage_matches['away_team_id'] == team_id]
        
        # Aggregate stats 
        wins = len(home_matches[home_matches['result'] == 'home_win']) + \
               len(away_matches[away_matches['result'] == 'away_win'])
        draws = len(home_matches[home_matches['result'] == 'draw']) + \
                len(away_matches[away_matches['result'] == 'draw'])
        losses = len(home_matches[home_matches['result'] == 'away_win']) + \
                 len(away_matches[away_matches['result'] == 'home_win'])
        
        goals_for = home_matches['home_score'].sum() + away_matches['away_score'].sum()
        goals_against = home_matches['away_score'].sum() + away_matches['home_score'].sum()
        goal_diff = goals_for - goals_against
        
        points = wins * 3 + draws * 1
        matches_played = len(home_matches) + len(away_matches)
        
        # Track opponents for H2H tiebreaker
        opponents_beat = list(home_matches[home_matches['result'] == 'home_win']['away_team_id'].values) + \
                         list(away_matches[away_matches['result'] == 'away_win']['home_team_id'].values)
        opponents_drew_with = list(home_matches[home_matches['result'] == 'draw']['away_team_id'].values) + \
                              list(away_matches[away_matches['result'] == 'draw']['home_team_id'].values)
        
        standings_data.append({
            'team_id': team_id,
            'team_name': team_name,
            'group': group,
            'matches_played': matches_played,
            'wins': wins,
            'draws': draws,
            'losses': losses,
            'points': points,
            'goals_for': goals_for,
            'goals_against': goals_against,
            'goal_diff': goal_diff,
            'opponents_beat': opponents_beat,
            'opponents_drew_with': opponents_drew_with,
        })
    
    return pd.DataFrame(standings_data)


def find_tied_teams(standings, rank_column='overall_rank'):
    """
    Identify teams tied on a given rank column within a group.
    
    Returns teams grouped by their rank value so tied teams can be processed together.
    
    Args:
        standings (pd.DataFrame): Standings table with columns: group, team_id, team_name, and rank_column
        rank_column (str): Name of the column to check for ties (default 'overall_rank')
    
    Returns:
        dict: Mapping of {rank_value: list of team_ids at that rank}
              Only includes ranks where 2+ teams are tied.
    
    Example:
        >>> ties = find_tied_teams(standings, group='A', rank_column='overall_rank')
        >>> # Result: {1: [4, 7], 3: [12, 15, 18]}  (2 teams tied for 1st) (3 teams tied for 3rd) 
    """
    group_standings = standings.copy()
    
    # Find which rank values have more than one team
    rank_counts = group_standings[rank_column].value_counts()
    tied_ranks = rank_counts[rank_counts > 1].index.tolist()
    
    # Build a dict: {rank_value: [list of team_ids at that rank]}
    tied_teams_dict = {}
    for rank_val in tied_ranks:
        tied_teams = group_standings[group_standings[rank_column] == rank_val]['team_id'].tolist()
        tied_teams_dict[rank_val] = tied_teams
    
    return tied_teams_dict




# ============================================================
# SECTION 4 — TIEBREAKERS
# ============================================================

def apply_h2h_tiebreaker(standings, group_stage_matches, tied_team_ids):
    """
    Apply the FIFA 2026 7-step tiebreaker to resolve a points tie within a group.

    Called with the full tied set at the start. Internally handles all sub-cases
    (2-team, 3-team, 4-team) and recurses when a partial resolution is found.

    Tiebreaker steps (per FIFA 2026 regulations):
      Step 2: H2H points among tied teams
        - 2-team tie: if resolved → done; else skip to Step 5
        - 3-team tie: if partial → recurse with sub-tied teams; if all still tied → Step 3
        - 4-team tie: skip directly to Step 5 (all group matches are relevant)
      Step 3: H2H goal difference (3-team only, same matches as Step 2)
        - if partial → recurse with sub-tied teams; if all still tied → Step 4
      Step 4: H2H goals scored (3-team only, same matches as Step 2/3)
        - if partial → recurse with sub-tied teams; if all still tied → Step 5
      Step 5: Overall goal difference (from standings)
      Step 6: Overall goals scored (from standings)
      Step 7: Equal probability coin flip (random); recurse if 3-team tie remains

    Args:
        standings (pd.DataFrame): Group standings with columns:
            team_id, points, goal_diff, goals_for
        group_stage_matches (pd.DataFrame): All matches in this group with columns:
            home_team_id, away_team_id, home_score, away_score, result
        tied_team_ids (list[int]): Team IDs currently tied on points.
            Must have length 2, 3, or 4.

    Returns:
        dict[int, int]: {team_id: rank} for each tied team.
            Ranks are 1-based and relative to this tied subset only.
            The caller (apply_all_tiebreakers) is responsible for offsetting
            these ranks by the number of teams already ranked above this group.

    Raises:
        ValueError: if tied_team_ids has fewer than 2 or more than 4 teams.
    """

    n = len(tied_team_ids)

    if n < 2 or n > 4:
        raise ValueError(
            f"apply_h2h_tiebreaker expects 2, 3, or 4 tied teams. Got {n}: {tied_team_ids}"
        )

    logger.debug("Tiebreaker called for %d teams: %s", n, tied_team_ids)

    # ------------------------------------------------------------------
    # Helper: assign standard ranks (1,2,2,4) from a sorted score dict.
    # Returns a full {team_id: rank} dict if all teams are separated,
    # or None if any teams remain tied (so the caller can continue).
    # Also returns the sub-groups still tied as a list of lists.
    # ------------------------------------------------------------------
    def _rank_from_scores(score_dict):
        """
        Given {team_id: numeric_score}, produce standard (1,2,2,4) ranks.

        Returns:
            ranks (dict): {team_id: rank} — always populated
            still_tied_groups (list[list]): each inner list is a group of
                team_ids that share the same score and need further resolution.
                Empty list means fully resolved.
        """
        sorted_teams = sorted(score_dict.items(), key=lambda x: x[1], reverse=True)
        ranks = {}
        still_tied_groups = []
        i = 0
        while i < len(sorted_teams):
            current_score = sorted_teams[i][1]
            # Collect all teams at this score level
            group = [t for t, s in sorted_teams if s == current_score]
            rank = i + 1  # standard ranking: rank = position of first in group
            for team_id in group:
                ranks[team_id] = rank
            if len(group) > 1:
                still_tied_groups.append(group)
            i += len(group)
        return ranks, still_tied_groups

    # ------------------------------------------------------------------
    # Helper: compute H2H stats for a set of teams from their shared matches.
    # Returns three dicts: h2h_points, h2h_gd, h2h_gf — all keyed by team_id.
    # Pre-computed once and reused across steps 2, 3, 4.
    # ------------------------------------------------------------------
    def _compute_h2h_stats(team_ids):
        h2h_matches = group_stage_matches[
            group_stage_matches['home_team_id'].isin(team_ids) &
            group_stage_matches['away_team_id'].isin(team_ids)
        ]

        h2h_points = {}
        h2h_gd = {}
        h2h_gf = {}

        for team_id in team_ids:
            home = h2h_matches[h2h_matches['home_team_id'] == team_id]
            away = h2h_matches[h2h_matches['away_team_id'] == team_id]

            wins  = len(home[home['result'] == 'home_win']) + \
                    len(away[away['result'] == 'away_win'])
            draws = len(home[home['result'] == 'draw']) + \
                    len(away[away['result'] == 'draw'])

            gf = home['home_score'].sum() + away['away_score'].sum()
            ga = home['away_score'].sum() + away['home_score'].sum()

            h2h_points[team_id] = wins * 3 + draws * 1
            h2h_gd[team_id]     = gf - ga
            h2h_gf[team_id]     = gf

        return h2h_points, h2h_gd, h2h_gf

    # ------------------------------------------------------------------
    # Helper: read overall stats from standings for a set of team_ids.
    # ------------------------------------------------------------------
    def _overall_stats(team_ids):
        subset = standings[standings['team_id'].isin(team_ids)]
        gd = {row['team_id']: row['goal_diff'] for _, row in subset.iterrows()}
        gf = {row['team_id']: row['goals_for']  for _, row in subset.iterrows()}
        return gd, gf

    # ------------------------------------------------------------------
    # Helper: merge partial tiebreaker results back into a full rank dict.
    # partial_ranks: {team_id: rank} for the sub-tied group
    # base_rank: the rank at which this sub-group sits (1-based offset)
    # full_ranks: the dict being built for all tied_team_ids
    # ------------------------------------------------------------------
    def _merge_ranks(full_ranks, partial_ranks, base_rank):
        for team_id, rel_rank in partial_ranks.items():
            full_ranks[team_id] = base_rank + rel_rank - 1

    # ==================================================================
    # STEP 5 / 6 / 7 — Overall stats fallback (shared by all tie sizes)
    # Applied to whatever sub-set of teams is still tied at this point.
    # Returns a rank dict for those teams (1-based, relative).
    # ==================================================================
    def _steps_5_6_7(still_tied):
        overall_gd, overall_gf = _overall_stats(still_tied)

        # Step 5: overall goal difference
        ranks_5, tied_after_5 = _rank_from_scores(overall_gd)
        logger.debug("  Step 5 (Overall GD): %s", overall_gd)

        if not tied_after_5:
            logger.debug("    ✓ Resolved by overall GD")
            return ranks_5

        # Build full ranks for separated teams; recurse into still-tied sub-groups
        result = {}
        for team_id, rank in ranks_5.items():
            result[team_id] = rank

        for sub_tied in tied_after_5:
            base_rank = ranks_5[sub_tied[0]]

            # Step 6: overall goals scored
            sub_gf = {t: overall_gf[t] for t in sub_tied}
            ranks_6, tied_after_6 = _rank_from_scores(sub_gf)
            logger.debug("  Step 6 (Overall GF) for %s: %s", sub_tied, sub_gf)

            if not tied_after_6:
                logger.debug("    ✓ Resolved by overall GF")
                _merge_ranks(result, ranks_6, base_rank)
                continue

            # Step 7: equal probability coin flip
            # Each remaining tied sub-group gets randomly ordered.
            # If exactly 2 teams remain: 50/50. If 3 remain: equal 1/3 each.
            # After the flip, any teams that were in a larger group re-enter
            # from step 2 — handled here by a recursive call for the losers.
            logger.debug(
                "  Step 7 (Fair Play / Coin Flip) for %s — assigning randomly",
                sub_tied
            )
            # Assign the already-resolved teams from step 6 first
            for team_id, rank in ranks_6.items():
                result[team_id] = base_rank + rank - 1

            for coin_group in tied_after_6:
                coin_base = base_rank + ranks_6[coin_group[0]] - 1
                shuffled = coin_group.copy()
                random.shuffle(shuffled)
                for i, team_id in enumerate(shuffled):
                    result[team_id] = coin_base + i

        return result

    # ==================================================================
    # MAIN DISPATCH — branch on tie size
    # ==================================================================

    # ---- 4-TEAM TIE --------------------------------------------------
    # All matches in the group involve the tied teams, so H2H steps 2-4
    # are not meaningful. Go directly to overall stats.
    if n == 4:
        logger.debug("4-team tie: skipping H2H steps, going to Step 5")
        return _steps_5_6_7(tied_team_ids)

    # ---- 2-TEAM TIE --------------------------------------------------
    # Step 2: H2H points (1 match). If resolved → done.
    # Steps 3-4 are redundant for 2 teams (H2H GD/GF after H2H points
    # adds no information with a single match). Jump to Step 5.
    if n == 2:
        h2h_pts, _, _ = _compute_h2h_stats(tied_team_ids)
        logger.debug("2-team tie — Step 2 (H2H Points): %s", h2h_pts)

        ranks_2, still_tied = _rank_from_scores(h2h_pts)
        if not still_tied:
            logger.debug("    ✓ Resolved by H2H points")
            return ranks_2

        # Still tied: skip to Step 5
        logger.debug("    H2H points did not resolve 2-team tie. Going to Step 5.")
        return _steps_5_6_7(tied_team_ids)

    # ---- 3-TEAM TIE --------------------------------------------------
    # Pre-compute H2H stats once for all three H2H steps.
    h2h_pts, h2h_gd_dict, h2h_gf_dict = _compute_h2h_stats(tied_team_ids)

    # Step 2: H2H points
    logger.debug("3-team tie — Step 2 (H2H Points): %s", h2h_pts)
    ranks_2, still_tied_2 = _rank_from_scores(h2h_pts)

    if not still_tied_2:
        logger.debug("    ✓ Resolved by H2H points")
        return ranks_2

    # Partial resolution: one team separated, two remain tied.
    # Restart from Step 2 with the two remaining teams.
    if len(still_tied_2) == 1 and len(still_tied_2[0]) == 2:
        sub_tied = still_tied_2[0]
        base_rank = ranks_2[sub_tied[0]]
        logger.debug(
            "    Partial resolution at Step 2. Restarting Step 2 with %s", sub_tied
        )
        result = {t: ranks_2[t] for t in tied_team_ids if t not in sub_tied}
        sub_result = apply_h2h_tiebreaker(standings, group_stage_matches, sub_tied) # recursive call with the 2-team tie. the function is calling itself! is that possible? yes.
        _merge_ranks(result, sub_result, base_rank) 
        return result

    # All 3 still tied → Step 3: H2H goal difference
    logger.debug("  Step 3 (H2H GD): %s", h2h_gd_dict)
    ranks_3, still_tied_3 = _rank_from_scores(h2h_gd_dict)

    if not still_tied_3:
        logger.debug("    ✓ Resolved by H2H GD")
        return ranks_3

    if len(still_tied_3) == 1 and len(still_tied_3[0]) == 2:
        sub_tied = still_tied_3[0]
        base_rank = ranks_3[sub_tied[0]]
        logger.debug(
            "    Partial resolution at Step 3. Restarting Step 2 with %s", sub_tied
        )
        result = {t: ranks_3[t] for t in tied_team_ids if t not in sub_tied}
        sub_result = apply_h2h_tiebreaker(standings, group_stage_matches, sub_tied)
        _merge_ranks(result, sub_result, base_rank)
        return result

    # All 3 still tied → Step 4: H2H goals scored
    logger.debug("  Step 4 (H2H GF): %s", h2h_gf_dict)
    ranks_4, still_tied_4 = _rank_from_scores(h2h_gf_dict)

    if not still_tied_4:
        logger.debug("    ✓ Resolved by H2H GF")
        return ranks_4

    if len(still_tied_4) == 1 and len(still_tied_4[0]) == 2:
        sub_tied = still_tied_4[0]
        base_rank = ranks_4[sub_tied[0]]
        logger.debug(
            "    Partial resolution at Step 4. Restarting Step 2 with %s", sub_tied
        )
        result = {t: ranks_4[t] for t in tied_team_ids if t not in sub_tied}
        sub_result = apply_h2h_tiebreaker(standings, group_stage_matches, sub_tied)
        _merge_ranks(result, sub_result, base_rank)
        return result

    # All 3 still tied after H2H steps → Step 5/6/7
    logger.debug("  All H2H steps exhausted. Going to Step 5.")
    return _steps_5_6_7(tied_team_ids)


def apply_all_tiebreakers(standings, group_stage_matches):
    """
    For each group, identify any ties in the initial rankings and apply the full tiebreaker process.

    Modifies the standings DataFrame in-place to update the 'overall_rank' column with the final ranks after tiebreakers.

    Args:
        standings (pd.DataFrame): Initial standings with columns: team_id, group, overall_rank, goal_diff, goals_for
        group_stage_matches (pd.DataFrame): All matches in this group with columns:
            home_team_id, away_team_id, home_score, away_score, result, group_id (or derive from teams_df)
    """
    # Add guard to filter for stage_id == 1 if present
    if 'stage_id' in group_stage_matches.columns:
        group_stage_matches = group_stage_matches[
            group_stage_matches['stage_id'] == 1
        ]


    final_rankings = {}
    for group in standings['group'].unique():
        group_standings = standings[standings['group'] == group]
        ranked_group_standings = initial_ranking(group_standings)
        tied_teams = find_tied_teams(ranked_group_standings) # <-- example: {1: [4, 7], 3: [12, 15, 18]}
        if tied_teams:
            logger.debug("Tied teams in Group %s:", group)
            for position, teams in tied_teams.items():
                logger.debug("  Position %s: Teams %s", position, teams)
                broken_ties = apply_h2h_tiebreaker(ranked_group_standings, group_stage_matches, teams)
                logger.debug("    → H2H tiebreaker ranks: %s", broken_ties)
                ## Update the overall_rank in the final standings based on the tiebreaker results 
                for team_id, relative_rank in broken_ties.items():
                    ranked_group_standings.loc[ranked_group_standings['team_id'] == team_id, 'overall_rank'] = \
                        ranked_group_standings.loc[ranked_group_standings['team_id'] == team_id, 'overall_rank'] + relative_rank - 1
        final_rankings[group] = ranked_group_standings

    final_standings = pd.concat(final_rankings.values(), ignore_index=True)
    return final_standings
    
                
def rank_third_place_teams(final_standings: pd.DataFrame, scenarios: dict) -> tuple[pd.DataFrame, dict]:
    """
    Rank all 12 third-place finishers to find the 8 that advance to the Round of 32.
    Then look up the correct bracket scenario from the 495 pre-defined FIFA matchups.

    Called after apply_all_tiebreakers() has resolved all group standings and
    every team has a definitive overall_rank of 1, 2, 3, or 4.

    Cross-group ranking criteria (no H2H — teams never played each other):
      1. Points
      2. Goal difference (all group matches)
      3. Goals scored (all group matches)
      4. Fair play score — omitted here, treated as equal (see note below)
      5. FIFA World Ranking — omitted here, treated as equal (see note below)
      6. Coin flip (random) — final fallback

    Note on steps 4 & 5: fair_play_score and fifa_ranking are not currently
    stored in final_standings. When those columns are added, insert them into
    the sort_values() call below in place of the random fallback.

    Args:
        final_standings (pd.DataFrame): Output of apply_all_tiebreakers().
            Must have columns: team_id, team_name, group, overall_rank,
            points, goal_diff, goals_for.
        scenarios (dict): The THIRD_PLACE_SCENARIOS_BY_GROUPS dictionary
            imported from third_place_scenarios.py.

    Returns:
        tuple:
            - third_place_df (pd.DataFrame): All 12 third-place teams sorted
              by cross-group rank. Includes columns:
                cross_group_rank (int): 1–12, where 1 is best
                advances (bool): True for ranks 1–8, False for 9–12
            - scenario (dict): The matched scenario dict from THIRD_PLACE_SCENARIOS_BY_GROUPS,
              e.g. {"scenario": 45, "slots": {"1A": "3C", "1B": "3G", ...}}
              Returns None if scenario lookup fails (should not happen in a
              valid simulation).

    Raises:
        ValueError: if final_standings does not contain exactly 12 teams
                    with overall_rank == 3 (one per group).
    """

    # --- Step 1: Extract the third-place finisher from each of the 12 groups ---
    third_place_df = final_standings[final_standings['overall_rank'] == 3].copy()

    if len(third_place_df) != 12:
        raise ValueError(
            f"Expected 12 third-place teams (one per group), found {len(third_place_df)}. "
            "Ensure apply_all_tiebreakers() has been called and all groups are resolved."
        )

    # --- Step 2: Add a random tiebreak column as the final fallback (step 6) ---
    # This stands in for fair play score + FIFA ranking until those columns exist.
    # When fair_play_score and fifa_ranking are added to standings, replace this
    # with: sort_values(['points', 'goal_diff', 'goals_for', 'fair_play_score',
    #                    'fifa_ranking'], ascending=[False, False, False, False, True])
    third_place_df['_random_tiebreak'] = [random.random() for _ in range(len(third_place_df))]

    # --- Step 3: Sort by cross-group criteria ---
    third_place_df = third_place_df.sort_values(
        by=['points', 'goal_diff', 'goals_for', '_random_tiebreak'],
        ascending=[False, False, False, False]
    ).reset_index(drop=True)

    # --- Step 4: Assign cross-group rank (1 = best, 12 = worst) ---
    third_place_df['cross_group_rank'] = range(1, 13)
    third_place_df['advances'] = third_place_df['cross_group_rank'] <= 8

    # Drop the internal tiebreak column — not meaningful to expose
    third_place_df = third_place_df.drop(columns=['_random_tiebreak'])

    logger.debug("Third-place rankings:")
    for _, row in third_place_df.iterrows():
        logger.debug(
            "  %2d. Group %s — %s  (pts=%d, gd=%+d, gf=%d) advances=%s",
            row['cross_group_rank'], row['group'], row['team_name'],
            row['points'], row['goal_diff'], row['goals_for'], row['advances']
        )

    # --- Step 5: Look up the bracket scenario ---
    advancing = third_place_df[third_place_df['advances']]
    qualifying_groups = sorted(advancing['group'].tolist())
    scenario_key = ','.join(qualifying_groups)

    scenario = scenarios.get(scenario_key, None)

    if scenario is None:
        logger.warning(
            "Scenario key '%s' not found in scenarios dictionary. "
            "Check group letters are single uppercase characters A–L.",
            scenario_key
        )
    else:
        logger.debug(
            "Matched scenario %d for groups [%s]",
            scenario['scenario'], scenario_key
        )

    return third_place_df, scenario

# ============================================================
# SECTION 5 — THIRD PLACE & BRACKET
# ============================================================
def determine_r32_matchups(final_standings, third_place_scenario) -> list[dict]:
    """
    Determine the Round of 32 matchups based on group winners, runners-up, and the ranked third-place teams.

    Args:
        final_standings (pd.DataFrame): Output of apply_all_tiebreakers() with columns:
            team_id, team_name, group, overall_rank.
        third_place_scenario (dict): The matched scenario dict from THIRD_PLACE_SCENARIOS_BY_GROUPS,
            e.g. {"scenario": 45, "slots": {"1A": "3C", "1B": "3G", ...}}.

    Returns:
        list[dict]: List of 16 matchups for the Round of 32. Each matchup is a dictionary:
            home_team_id: team1 id, 'home_team_name': team1 name, 
            'away_team_id': team2 id, 'away_team_name': team2 name,
            where team1 is the higher-seeded team (group winner or runner-up) and
            team2 is the lower-seeded team (runner-up or third-place finisher).
    """

    # --- Step 1: Create a mapping of group positions to teams ---
    position_to_team = {}
    for _, row in final_standings.iterrows():
        # # "1A", "2B", etc. Note: overall_rank is a float due to the ranking process, so we format it as an integer string.
        key = f"{int(row['overall_rank'])}{row['group']}" 
        position_to_team[key] = (row['team_id'], row['team_name']) # e.g. "1A" → (4, "Brazil"), "2B" → (15, "France"), "3C" → (27, "Japan")
        logger.debug(f"Mapping position '{key}' to team '{row['team_name']}' (ID: {row['team_id']})")

    # --- Step 2: Build matchups based on the scenario slots ---
    matchups = []
    for slot1, slot2 in third_place_scenario['slots'].items():
        team1 = position_to_team.get(slot1)
        team2 = position_to_team.get(slot2)

        if team1 is None or team2 is None:
            logger.warning(
                "Missing team for slot '%s' or '%s'. Check standings and scenario slots.",
                slot1, slot2
            )
            continue

        matchups.append({
            'home_team_id':   team1[0],
            'home_team_name': team1[1],
            'away_team_id':   team2[0],
            'away_team_name': team2[1],
            })

    return matchups


def run_simulation(teams_df: pd.DataFrame, matches_df: pd.DataFrame) -> tuple:
    """
    Run one full end-to-end simulation of the group stage.

    Simulates unplayed matches, combines with completed results,
    computes standings, applies tiebreakers, ranks third-place teams,
    and determines Round of 32 matchups.

    Args:
        teams_df (pd.DataFrame): Teams table from DB.
        matches_df (pd.DataFrame): Full matches table from DB (all 104 rows).

    Returns:
        tuple:
            final_final_ranked (pd.DataFrame): Full standings with resolved ranks.\\
            third_place_df (pd.DataFrame): Ranked third-place teams.\\
            scenario (dict): Matched third-place bracket scenario.\\
            r32_matchups (list[tuple]): 8 third-place R32 matchups.\\
            simulated_matches (pd.DataFrame): The simulated match scores.
    """
    simulated_matches = simulate_group_stage_matches_fifa(matches_df, teams_df)

    # Get already-completed real matches
    completed_matches = matches_df[
        (matches_df['stage_id'] == 1) &
        (matches_df['status'] == 'completed')
    ].copy()

    # Combine into one full group stage picture
    all_group_matches = pd.concat([completed_matches, simulated_matches], ignore_index=True)


    final_standings = create_final_standings(all_group_matches, teams_df)

    # Now that we have the final standings, let's go group by group to get rankings

    final_final_ranked = apply_all_tiebreakers(final_standings, all_group_matches)

    # After your pipeline runs:
    third_place_df, scenario = rank_third_place_teams(final_final_ranked, THIRD_PLACE_SCENARIOS_BY_GROUPS)

    r32_matchups = determine_r32_matchups(final_final_ranked, scenario)


    return final_final_ranked, third_place_df, scenario, r32_matchups, simulated_matches


# ============================================================
# SECTION 6 — SIMULATION ORCHESTRATION
# ============================================================
if __name__ == "__main__":
    matches_df, teams_df = load_data()
    tally_to_r32 = {team: 0 for team in teams_df['team_name']}

    for i in range(1, N_SIMULATIONS + 1):
        final_standings, third_place_df, scenario, r32_matchups, _ = run_simulation(
            teams_df=teams_df, matches_df=matches_df
        )
        for _, row in final_standings.iterrows():
            team_name = row['team_name']
            slot_key = f"{int(row['overall_rank'])}{row['group']}"
            advances = (
                row['overall_rank'] < 3 or
                slot_key in scenario['slots'].values()
            )
            if advances:
                tally_to_r32[team_name] += 1

        print(f"{i}/{N_SIMULATIONS}")

    print(tally_to_r32)